### ISSUE TITLE
SDL2 in Ubuntu 20.04 (WSL)

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#10]
sudo apt-get install libsdl2 gives following error:

E: Unable to locate package libsdl2.

WSL:
Windows 10 Linux Subsystem
RELEASE:  Ubuntu 20.04.4 LTS
KERNEL:   Linux 5.10.102.1-microsoft-standard-WSL2

**Comment by mail2mhossain** [comment]
Solved the issue.

What you need to do to install SDL is: (https://gist.github.com/aaangeletakis/3187339a99f7786c25075d4d9c80fad5)

#install sdl2
sudo apt install libsdl2-dev libsdl2-2.0-0 -y;

#install sdl image  - if you want to display images
sudo apt install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0 -y;

#install sdl mixer  - if you want sound
sudo apt install libmikmod-dev libfishsound1-dev libsmpeg-dev liboggz2-dev libflac-dev libfluidsynth-dev libsdl2-mixer-dev libsdl2-mixer-2.0-0 -y;

#install sdl true type fonts - if you want to use text
sudo apt install libfreetype6-dev libsdl2-ttf-dev libsdl2-ttf-2.0-0 -y;

**Comment by ChristopheI** [comment]
I will close the issue, as it seems solved.

Feel free to ask any other question, or reopen issue.
