### ISSUE TITLE
Is it possible to get an event when source or endpoint change in client app

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#11]
Is there any way two get an event when source or endpoint change in client app?

Is there any way to change source or endpoint at runtime?

**Comment by ChristopheI** [comment]
> Is there any way two get an event when source or endpoint change in client app?

SDL2 library provides this kind of events but it's not yet available in [SIPSorceryMedia.SDL2](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2).

Don't hesitate to create a new PR :)
