### ISSUE TITLE
sending opus encoded audio with webrtc

### ISSUE THREAD

**Issue by hassan379** [sipsorcery-org/SIPSorceryMedia.SDL2#12]
Hi
I am trying to capture windows desktop sound using WasapiLoopbackCapture
`waveIn = new WasapiLoopbackCapture();`
`waveIn.WaveFormat = new WaveFormat(48000 , 16 , 1);`
`waveIn.DataAvailable += LocalAudioSampleAvailable;`
and I want to encode the received buffers in LocalAudioSampleAvailable with opus audio encoder , so I made some changes in WindowsAudioEndPoint 
https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/blob/master/src/WindowsAudioEndPoint.cs
`WindowsAudioEndPoint audioSource = new WindowsAudioEndPoint(new OpusAudioEncoder());`
`audioSource.RestrictFormats(format => format.Codec == AudioCodecsEnum.OPUS);`
but when I run my app , I get error in  "chrome and Edge"
"Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote audio description send parameters for m-section with mid='0'."
I fixed that by changing this line inside "OpusAudioEncoder" class
https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2/blob/main/test/CheckCodec/OpusAudioEncoder.cs
` public static readonly AudioFormat MEDIA_FORMAT_OPUS = new AudioFormat(111, "opus", SAMPLE_RATE, SAMPLE_RATE, 2, "a=fmtp:111 minptime=10;useinbandfec=1");
`
with this line
` public static readonly AudioFormat MEDIA_FORMAT_OPUS = new AudioFormat(AudioCodecsEnum.OPUS, 111, SAMPLE_RATE, SAMPLE_RATE, 2, "a=fmtp:111 minptime=10;useinbandfec=1");`
the problem is , I cant get the sound at the end correctly and I don't know why , the following code shows how I am encoding the buffers when I get them from WasapiLoopbackCapture inside LocalAudioSampleAvailable
       
```
private void LocalAudioSampleAvailable(object sender, WaveInEventArgs args)
        {
            // Note NAudio.Wave.WaveBuffer.ShortBuffer does not take into account little endian.
            // https://github.com/naudio/NAudio/blob/master/NAudio/Wave/WaveOutputs/WaveBuffer.cs
            //WaveBuffer wavBuffer = new WaveBuffer(args.Buffer.Take(args.BytesRecorded).ToArray());
            //byte[] encodedSample = _audioEncoder.EncodeAudio(wavBuffer.ShortBuffer, _audioFormatManager.SelectedFormat);
            try
            {
                byte[] buffer = args.Buffer.Take(args.BytesRecorded).ToArray();
                short[] pcm = buffer.Where((x, i) => i % 2 == 0).Select((y, i) => BitConverter.ToInt16(buffer, i * 2)).ToArray();
                byte[] encodedSample = _audioEncoder.EncodeAudio(pcm, _audioFormatManager.SelectedFormat);

                //OnAudioSourceEncodedSample?.Invoke((uint)_audioFormatManager.SelectedFormat.RtpClockRate / 1000 * AUDIO_SAMPLE_PERIOD_MILLISECONDS, encodedSample);
                OnAudioSourceEncodedSample?.Invoke((uint)encodedSample.Length, encodedSample);
                //OnAudioSourceEncodedSample?.Invoke((uint)(pcm.Length * _audioFormatManager.SelectedFormat.RtpClockRate / _audioFormatManager.SelectedFormat.ClockRate), encodedSample);

            }
            catch (Exception ex)
            {

            }
        }
```

I am getting sound but it contains too much noise and it is not clear at all and the quality is very low , can you help me with this ?
many thanks

**Comment by hassan379** [comment]
After reading some basics about opus, I mad some changes in LocalAudioSampleAvailable but no success
```
                byte[] soundBuffer = new byte[args.BytesRecorded + _notEncodedBuffer.Length];
                Array.Copy(_notEncodedBuffer, 0, soundBuffer, 0, _notEncodedBuffer.Length);
                Array.Copy(args.Buffer, 0, soundBuffer, _notEncodedBuffer.Length, args.BytesRecorded);

                int byteCap = 2*960;// 2 * framesize to change bytes array later to shorts array
                int segmentCount = (int)Math.Floor((decimal)soundBuffer.Length / byteCap);
                int segmentsEnd = segmentCount * byteCap;
                int notEncodedCount = soundBuffer.Length - segmentsEnd;
                _notEncodedBuffer = new byte[notEncodedCount];
                Array.Copy(soundBuffer, segmentsEnd, _notEncodedBuffer, 0, notEncodedCount);

                for (int i = 0; i < segmentCount; i++)
                {
                    byte[] segment = new byte[byteCap];
                    Array.Copy(soundBuffer, (i * byteCap), segment, 0, segment.Length);
                    short[] pcm = segment.Where((x, d) => d % 2 == 0).Select((y, d) => BitConverter.ToInt16(segment, d * 2)).ToArray();
                    byte[] encodedSample = _audioEncoder.EncodeAudio(pcm, _audioFormatManager.SelectedFormat);
                    OnAudioSourceEncodedSample?.Invoke((uint)encodedSample.Length, encodedSample);
                }
```

**Comment by ChristopheI** [comment]
Hi,

Sorry but I never used [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows) package ...

He took me a long effort to support Opus in [SIPSorceryMedia.SDL2 ](https://github.com/sipsorcery-org/SIPSorceryMedia.SDL2): see this [comment](https://github.com/sipsorcery-org/sipsorcery/issues/518#issuecomment-1117301963) and previous ones it could help

If you need more information it will be better to ask in the correct repository

**Comment by hassan379** [comment]
ok , no problem i fixed that by replacing encodedSample.Length with pcm.length and its working now

**Comment by ChristopheI** [comment]
Could you propose a PR for this in [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows) ?

It will help a lot of people.

Thanks
