### ISSUE TITLE
In Linux (WSL-Ubuntu) "sudo apt-get install libsdl2" says "Unable to locate package libsdl2"

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#17]
In Linux (WSL-Ubuntu) "sudo apt-get install libsdl2" says "Unable to locate package libsdl2"

But "sudo apt install libsdl2-dev libsdl2-2.0-0 -y" is working. After installation "sudo apt install libsdl2-dev libsdl2-2.0-0 -y", SDL2 does not providing any choice to select audio input or output device. It only shows "RDP Source" as Audio Input and "RDP Sink" as audio output.

My built in mic is not working. Using external USB Mic. But SDL2 cannot recognize it.

Please help me solve this issue.

**Comment by wcjdev** [comment]
I ran across your post today and it was just what I needed to get my issue fixed. Every other post or site I saw before yours might as well as had engineering schematics as complex as their responses were.
