### ISSUE TITLE
Changing audio source and end point while in call (replaceTrack)

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#19]
Is there any way to change audio source and end point in already connected RTCPeerConnection that audio call is running in a webrtc environment.

Is there anyway to replace Track?

**Comment by ChristopheI** [comment]
You have created three time the same ticket ....
This one and these two.
https://github.com/sipsorcery-org/sipsorcery/issues/960
https://github.com/sipsorcery-org/sipsorcery/issues/972

Congratulations !
