### ISSUE TITLE
Echo in sound

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#22]
When using the laptop's built-in speaker and microphone, there is a tendency for echo to occur. However, this issue does not arise when headphones are used.

Is there any echo/noise cancellation feature in SIPSorceryMedia.SDL2?

Code:
_audioEncoder = new OpusAudioEncoder();
_audioFormat = OpusAudioEncoder.MEDIA_FORMAT_OPUS;

_frameSize = _audioEncoder.GetFrameSize();
_audioSource = new SDL2AudioSource(AudioInputName, _audioEncoder, (uint)_frameSize);
_audioEndPoint = new SDL2AudioEndPoint(AudioOutputName, _audioEncoder);

**Comment by ChristopheI** [comment]
There is no echo cancellation available
Don't hesitate to create a PR and participate to SIPSorcery projects
