### ISSUE TITLE
GetAudioPlaybackDevices() & GetAudioPlaybackDevices methods of SDL2Helper class returns empty list

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#4]
I am using SIPSorceryMedia.SDL2, version 1.0.0 from nuget.

As per Document, 'No additional steps are required for an x64 build. The nuget package includes the SDL v2.0.20 x64 binaries'. But without manually download the library, I am getting error (Unable to load DLL 'SDL2').

Both GetAudioPlaybackDevices() & GetAudioPlaybackDevices of SDL2Helper class returns empty list.

**Comment by mail2mhossain** [comment]
Got it. Need to call SDL2Helper.InitSDL(); before calling GetAudioPlaybackDevices() & GetAudioPlaybackDevices

**Comment by ChristopheI** [comment]
> As per Document, 'No additional steps are required for an x64 build. The nuget package includes the SDL v2.0.20 x64 binaries'. But without manually download the library, I am getting error (Unable to load DLL 'SDL2').

You are right. SDL2.dll binary files is missing. I will add it in the repo.
Binary file must be in same folder than your executable

**Comment by ChristopheI** [comment]
> Got it. Need to call SDL2Helper.InitSDL(); before calling GetAudioPlaybackDevices() & GetAudioPlaybackDevices

Correct.   I will close the issue, as it seems solved.

Feel free to ask any other question, or reopen issue.
