### ISSUE TITLE
Am I in a right track to setup audio input and Output with Sipsorcery WebRTC lib

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#5]
_audioSource = new SDL2AudioSource(AudioInputName, new AudioEncoder());
            _audioSink = new SDL2AudioEndPoint(AudioOutputName, new AudioEncoder());

            MediaStreamTrack audioInputTrack = new MediaStreamTrack(_audioSource.GetAudioSourceFormats(),
                MediaStreamStatusEnum.SendOnly);
            _peerConnection.addTrack(audioInputTrack);

            _audioSource.OnAudioSourceEncodedSample += _peerConnection.SendAudio;
            _peerConnection.OnRtpPacketReceived += (IPEndPoint rep, SDPMediaTypesEnum media, RTPPacket rtpPkt) =>
            {
                if (media == SDPMediaTypesEnum.audio)
                {
                    _audioSink.GotAudioRtp(rep, rtpPkt.Header.SyncSource,
                        rtpPkt.Header.SequenceNumber, rtpPkt.Header.Timestamp,
                        rtpPkt.Header.PayloadType, rtpPkt.Header.MarkerBit == 1,
                        rtpPkt.Payload);
                }
            };

            _peerConnection.OnAudioFormatsNegotiated += (audioFormats) =>
            {
                _audioSource.SetAudioSourceFormat(audioFormats.First());
                _audioSink.SetAudioSinkFormat(audioFormats.First());
            };

**Comment by ChristopheI** [comment]
It seems ok.

Since you added a track using "SendOnly" the remote peer could hear you but the local peer will not received sound from remote

**Comment by mail2mhossain** [comment]
Using above code with "MediaStreamStatusEnum.SendRecv", did not get any audio.  I am also calling await _audioSource.StartAudio().ConfigureAwait(false); and await _audioSink.StartAudioSink().ConfigureAwait(false);
FYI:
![AudioBridge_SDL2_01](https://user-images.githubusercontent.com/6905164/165211106-df114ddf-4fc7-4cd8-8bc6-b629326cf23b.png)
![AudioBridge_SDL2_02](https://user-images.githubusercontent.com/6905164/165211138-6242e7a6-642b-4aab-822f-28274a510048.png)

**Comment by ChristopheI** [comment]
The SDP negociation finished correctly ? you don't have codec issue ?
Today PCMU/PCMA is supported only in this lib.
Without specific config Janus is using OPUS by default

**Comment by mail2mhossain** [comment]
By default Janus AudioBridge supports "Opus". But it also supports "PCMA" & "PCMU".
If we want to offer G.711 and G.722, then we need to add codec: "pcmu" or codec: "pcma" to join request
and I am doing so.

I don't have codec issue. BTW: PeerConnection failed if their is codec issue.

**Comment by mail2mhossain** [comment]
Hi, does this library work with SipSorcery WebRTC? Do you have any example?

**Comment by ChristopheI** [comment]
Yes this library is working with SipSorcery. 
I'm using it every day in WebRTC Context. 
I just added G722 (fully tested) and it should work with G729 too (I haven't tested yet since I didn't find any client using it for the moment )

**Comment by mail2mhossain** [comment]
I have tried both "pcmu" and "pcma" with the following code:

        protected override void CreateAudioCaptureDevice()
        {
            AudioEncoder audioEncoder = new AudioEncoder();
            _audioSource = new SDL2AudioSource(AudioInputName, audioEncoder);
            _audioSink = new SDL2AudioEndPoint(AudioOutputName, audioEncoder);

            MediaStreamTrack audioInputTrack = new MediaStreamTrack(_audioSource.GetAudioSourceFormats(),
                MediaStreamStatusEnum.SendRecv);
            _peerConnection.addTrack(audioInputTrack);

            _audioSource.OnAudioSourceEncodedSample += _peerConnection.SendAudio;

            _peerConnection.OnRtpPacketReceived += (IPEndPoint rep, SDPMediaTypesEnum media, RTPPacket rtpPkt) =>
            {
                if (media == SDPMediaTypesEnum.audio)
                {
                    _audioSink.GotAudioRtp(rep, rtpPkt.Header.SyncSource,
                        rtpPkt.Header.SequenceNumber, rtpPkt.Header.Timestamp,
                        rtpPkt.Header.PayloadType, rtpPkt.Header.MarkerBit == 1,
                        rtpPkt.Payload);
                }
            };

            _peerConnection.OnAudioFormatsNegotiated += (audioFormats) =>
            {
                _audioSource.SetAudioSourceFormat(audioFormats.First());
                _audioSink.SetAudioSinkFormat(audioFormats.First());
            };
        }
        protected override async Task StartAudioVideoDevice()
        {
            await _audioSource.StartAudio().ConfigureAwait(false);
        }
       protected override async void _webRTC_OnPeerConnectionConnected(object sender, EventArgs e)
        {
            await _audioSink.StartAudioSink().ConfigureAwait(false);
        }

But still there is no audio. Cannot figure out the issue though peer connection is up.

BTW: "SIPSorceryMedia.Windows (WindowsAudioEndPoint)" is working fine in the same way.

**Comment by ChristopheI** [comment]
I will close the issue, as it seems solved. (cf. #9 )

Feel free to ask any other question, or reopen issue.
