### ISSUE TITLE
Failed to Send Audio

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.SDL2#9]
I can hear sound but it is not sending audio. Code is as follow:

OpusAudioEncoder audioEncoder = new OpusAudioEncoder();
            AudioFormat? audioFormat = OpusAudioEncoder.MEDIA_FORMAT_OPUS;

            _audioEndPoint = new SDL2AudioEndPoint(AudioOutputName, audioEncoder);
            _audioEndPoint.SetAudioSinkFormat(audioFormat.Value);

            int frameSize = audioEncoder.GetFrameSize();
            _audioSource = new SDL2AudioSource(AudioInputName, audioEncoder, (uint)frameSize);
            _audioSource.SetAudioSourceFormat(audioFormat.Value);

            MediaStreamTrack audioInputTrack = new MediaStreamTrack(_audioSource.GetAudioSourceFormats(),
                MediaStreamStatusEnum.SendRecv);
            _peerConnection.addTrack(audioInputTrack);

            _audioSource.OnAudioSourceEncodedSample += _peerConnection.SendAudio;

            _peerConnection.OnRtpPacketReceived += (IPEndPoint rep, SDPMediaTypesEnum media, RTPPacket rtpPkt) =>
            {
                if (media == SDPMediaTypesEnum.audio)
                {
                    _audioEndPoint.GotAudioRtp(rep, rtpPkt.Header.SyncSource,
                        rtpPkt.Header.SequenceNumber, rtpPkt.Header.Timestamp,
                        rtpPkt.Header.PayloadType, rtpPkt.Header.MarkerBit == 1,
                        rtpPkt.Payload);
                }
            };

            _peerConnection.OnAudioFormatsNegotiated += (audioFormats) =>
            {
                _audioSource.SetAudioSourceFormat(audioFormats.First());
                _audioEndPoint.SetAudioSinkFormat(audioFormats.First());
            };

**Comment by ChristopheI** [comment]
On connected (i.e RTCPeerConnectionState.connected), you must ensure to start AudioEndPoint and AudioSource (same for Video if you have some)
```
case RTCPeerConnectionState.connected:

    // Open/Start end points (video, audio, ...)
    
    if (AudioEndPoint != null)
        await AudioEndPoint.StartAudioSink();
    
    if (AudioSource != null)
        await AudioSource.StartAudio();
    
    if (VideoEndPoint != null)
        await VideoEndPoint.StartVideoSink();
    
    if (VideoSource != null)
        await VideoSource.StartVideo();
    
    if (VideoSecondaryEndPoint != null)
        await VideoSecondaryEndPoint.StartVideoSink();
    
    if (VideoSecondarySource != null)
        await VideoSecondarySource.StartVideo();
    break;
```

**Comment by mail2mhossain** [comment]
Thank you very much. now it is working. I am calling await AudioEndPoint.StartAudioSink(); only in RTCPeerConnectionState.connected. Now added await AudioSource.StartAudio(); too.

**Comment by ChristopheI** [comment]
I will close the issue, as it seems solved.

Feel free to ask any other question, or reopen issue.
